"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false 
scan_timeout = 8
# Give Python a little more breathing room on slower shell starts.
command_timeout = 1500
format = "$directory$hostname$git_branch$git_status$python$nodejs$dart$cmd_duration$line_break$character"
[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
symbol = '  '

[bun]
format = '\[[$symbol($version)]($style)\]'

[c]
format = '\[[$symbol($version(-$name))]($style)\]'
symbol = ' '

[cmake]
format = '\[[$symbol($version)]($style)\]'

[cmd_duration]
format = '\[[⏱ $duration]($style)\]'

[cobol]
format = '\[[$symbol($version)]($style)\]'

[conda]
format = '\[[$symbol$environment]($style)\]'
symbol = ' '

[crystal]
format = '\[[$symbol($version)]($style)\]'

[daml]
format = '\[[$symbol($version)]($style)\]'

[dart]
format = '\[[$symbol($version)]($style)\]'
symbol = ' '

[deno]
format = '\[[$symbol($version)]($style)\]'

[docker_context]
format = '\[[$symbol$context]($style)\]'
symbol = ' '

[dotnet]
format = '\\[[$symbol($version)(\U0001F3AF $tfm)]($style)\\]'

[elixir]
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'
symbol = ' '

[elm]
format = '\[[$symbol($version)]($style)\]'
symbol = ' '

[erlang]
format = '\[[$symbol($version)]($style)\]'

[fennel]
format = '\[[$symbol($version)]($style)\]'

[fossil_branch]
format = '\[[$symbol$branch]($style)\]'
symbol = ' '

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[git_branch]
format = '\[[$symbol$branch]($style)\]'
symbol = ' '

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
format = '\[[$symbol($version)]($style)\]'
symbol = ' '

[gradle]
format = '\[[$symbol($version)]($style)\]'

[guix_shell]
format = '\[[$symbol]($style)\]'
symbol = ' '

[haskell]
format = '\[[$symbol($version)]($style)\]'
symbol = ' '

[haxe]
format = '\[[$symbol($version)]($style)\]'
symbol = '⌘ '

[helm]
format = '\[[$symbol($version)]($style)\]'

[hg_branch]
format = '\[[$symbol$branch]($style)\]'
symbol = ' '

[java]
format = '\[[$symbol($version)]($style)\]'
symbol = ' '

[julia]
format = '\[[$symbol($version)]($style)\]'
symbol = ' '

[kotlin]
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[lua]
format = '\[[$symbol($version)]($style)\]'
symbol = ' '

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'
symbol = ' '

[meson]
format = '\[[$symbol$project]($style)\]'
symbol = '喝 '

[nim]
format = '\[[$symbol($version)]($style)\]'
symbol = ' '

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'
symbol = ' '

[nodejs]
format = '\[[$symbol($version)]($style)\]'
symbol = ' '

[ocaml]
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'

[opa]
format = '\[[$symbol($version)]($style)\]'

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\]'

[os]
format = '\[[$symbol]($style)\]'
[os.symbols]
Alpaquita = ' '
Alpine = ' '
Amazon = ' '
Android = ' '
Arch = ' '
Artix = ' '
CentOS = ' '
Debian = ' '
DragonFly = ' '
Emscripten = ' '
EndeavourOS = ' '
Fedora = ' '
FreeBSD = ' '
Garuda = '﯑ '
Gentoo = ' '
HardenedBSD = 'ﲊ '
Illumos = ' '
Linux = ' '
Mabox = ' '
Macos = ' '
Manjaro = ' '
Mariner = ' '
MidnightBSD = ' '
Mint = ' '
NetBSD = ' '
NixOS = ' '
OpenBSD = ' '
openSUSE = ' '
OracleLinux = ' '
Pop = ' '
Raspbian = ' '
Redhat = ' '
RedHatEnterprise = ' '
Redox = ' '
Solus = 'ﴱ '
SUSE = ' '
Ubuntu = ' '
Unknown = ' '
Windows = ' '

[package]
format = '\[[$symbol$version]($style)\]'
symbol = ' '

[perl]
format = '\[[$symbol($version)]($style)\]'

[php]
format = '\[[$symbol($version)]($style)\]'

[pijul_channel]
format = '\[[$symbol$channel]($style)\]'
symbol = '\U0001FABA '

[pulumi]
format = '\[[$symbol$stack]($style)\]'

[purescript]
format = '\[[$symbol($version)]($style)\]'

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
symbol = ' '

[raku]
format = '\[[$symbol($version-$vm_version)]($style)\]'

[red]
format = '\[[$symbol($version)]($style)\]'

[ruby]
format = '\[[$symbol($version)]($style)\]'
symbol = ' '

[rust]
format = '\[[$symbol($version)]($style)\]'
symbol = ' '

[scala]
format = '\[[$symbol($version)]($style)\]'
symbol = ' '

[spack]
format = '\[[$symbol$environment]($style)\]'
symbol = '\U0001F162 '

[sudo]
format = '\[[as $symbol]\]'

[swift]
format = '\[[$symbol($version)]($style)\]'

[terraform]
format = '\[[$symbol$workspace]($style)\]'

[time]
format = '\[[$time]($style)\]'

[username]
format = '\[[$user]($style)\]'

[vagrant]
format = '\[[$symbol($version)]($style)\]'

[vlang]
format = '\[[$symbol($version)]($style)\]'

[zig]
format = '\[[$symbol($version)]($style)\]'

[buf]
symbol = ' '

[directory]
read_only = ' '

[hostname]
ssh_only = true
format = '\[[$ssh_symbol$hostname]($style)\]'
ssh_symbol = ' '

[rlang]
symbol = 'ﳒ '
